USE [D:\USERS\FABIO\DOCUMENTS\CURSO EXERCICIOS\CURSO_CSHARP_IMPACTA\CONCEITOS.CSHARP.CAP13\COURSE\DBPRODUTOS.MDF]
GO

CREATE TABLE TBCategorias (
	Id INT IDENTITY(1,1),
	Descricao VARCHAR(20) NOT NULL,
	PRIMARY KEY(Id)
)
GO

CREATE TABLE TBProdutos (
	Id INT IDENTITY(1,1),
	IdCategoria INT NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	Preco FLOAT NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY(IdCategoria) REFERENCES TBCategorias(Id)
)
GO